import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { RouterProvider, createMemoryHistory, createRouter } from "@tanstack/react-router";
import { act, render, screen } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import * as hooks from "~/lib/hooks";
// Import routeTree from the generated file (regenerated by Vite plugin during build/dev)
import { routeTree } from "~/routes/../routeTree.gen";

// Mock the hooks module
vi.mock("~/lib/hooks", () => ({
  usePending: vi.fn(),
  useRecall: vi.fn(),
  useVerify: vi.fn(),
  useSchema: vi.fn(),
}));

async function renderWithRouter(pendingCount: number) {
  const mockUsePending = vi.mocked(hooks.usePending);
  mockUsePending.mockReturnValue({
    data: {
      proposals: Array.from({ length: pendingCount }, (_, i) => ({ hash: `hash${i}` })),
    },
    isLoading: false,
    isError: false,
    error: null,
  } as ReturnType<typeof hooks.usePending>);

  const router = createRouter({
    routeTree,
    history: createMemoryHistory({ initialEntries: ["/"] }),
  });
  const qc = new QueryClient({ defaultOptions: { queries: { retry: false } } });

  await act(async () => {
    render(
      <QueryClientProvider client={qc}>
        <RouterProvider router={router} />
      </QueryClientProvider>
    );
  });
}

describe("AppShell", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("renders all six nav areas", async () => {
    await renderWithRouter(0);
    expect(screen.getByRole("link", { name: /inbox/i })).toBeInTheDocument();
    expect(screen.getByRole("link", { name: /memory/i })).toBeInTheDocument();
    expect(screen.getByRole("link", { name: /schema/i })).toBeInTheDocument();
    expect(screen.getByRole("link", { name: /policy/i })).toBeInTheDocument();
    expect(screen.getByRole("link", { name: /verify/i })).toBeInTheDocument();
    expect(screen.getByRole("link", { name: /settings/i })).toBeInTheDocument();
  });

  it("shows inbox badge when there are pending proposals", async () => {
    await renderWithRouter(3);
    expect(screen.getByLabelText("3 pending")).toBeInTheDocument();
  });

  it("hides inbox badge when there are no pending proposals", async () => {
    await renderWithRouter(0);
    expect(screen.queryByLabelText(/pending/)).not.toBeInTheDocument();
  });
});
