/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is up */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/remember": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Write a scratch note */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RememberBody"];
                };
            };
            responses: {
                /** @description Admission result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RememberResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an entity */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateEntityBody"];
                };
            };
            responses: {
                /** @description Admission result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdmissionResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an entity by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Entity view */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Entity not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update an entity */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateEntityBody"];
                };
            };
            responses: {
                /** @description Admission result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdmissionResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Entity not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a relation (edge) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RelateBody"];
                };
            };
            responses: {
                /** @description Admission result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdmissionResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a classification */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClassifyBody"];
                };
            };
            responses: {
                /** @description Admission result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdmissionResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach a document */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AttachDocumentBody"];
                };
            };
            responses: {
                /** @description Admission result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdmissionResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List recent memories
         * @description Most recently indexed memories, newest first. Same result shape as recall (score is 0). The `status` query param maps to the `approval` field. With `scope=all`, returns the full workspace index instead — every non-meta node including pending proposals, as MemoryIndexEntry — and the other query params are ignored.
         */
        get: {
            parameters: {
                query?: {
                    scope?: string;
                    type?: string;
                    author?: string;
                    status?: string;
                    limit?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recent memories with provenance, or the full index with scope=all */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            results: components["schemas"]["RecallResult"][] | components["schemas"]["MemoryIndexEntry"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Memory graph export
         * @description All non-meta nodes and the typed edges between saved nodes, for the graph canvas.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Nodes and edges */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoryGraphView"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hybrid semantic recall
         * @description Semantic + full-text search fused via RRF. The `status` query param maps to the `approval` field in RecallResult.
         */
        get: {
            parameters: {
                query: {
                    q: string;
                    type?: string;
                    author?: string;
                    status?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recall results with provenance */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            results: components["schemas"]["RecallResult"][];
                        };
                    };
                };
                /** @description Missing query parameter q */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/{id}/traverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Traverse from an entity */
        get: {
            parameters: {
                query?: {
                    edgeTypes?: string;
                    direction?: "out" | "in" | "both";
                    depth?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Traversal results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pending proposals */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pending proposals */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            proposals: components["schemas"]["ProposalView"][];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/{hash}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a proposal */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    hash: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Approval result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Proposal not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/{hash}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a proposal */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    hash: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rejection result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Proposal not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify the graph integrity */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Integrity report */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VerifyReport"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rebuild the search index */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reindex complete */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/principals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List principals */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Principals list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new agent */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterAgentBody"];
                };
            };
            responses: {
                /** @description Agent registration result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Describe the schema */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Schema description */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SchemaDescription"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schema/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose an ontology change */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProposeOntologyBody"];
                };
            };
            responses: {
                /** @description Proposal result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schema/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Install an ontology (owner) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InstallOntologyBody"];
                };
            };
            responses: {
                /** @description Install result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get policy rules */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Policy rules list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Propose a policy change */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PolicyBody"];
                };
            };
            responses: {
                /** @description Policy proposal result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid JSON body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the changeset log */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Changeset log entries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get session config
         * @description Returns non-secret Freehold configuration (defaultAgent, embedder, port). The bearer token is NOT returned here — it is injected as a meta tag by the server.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session config */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionInfo"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graphs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registered graphs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All registered graphs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            graphs: components["schemas"]["GraphInfo"][];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Register a repo graph */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterGraphBody"];
                };
            };
            responses: {
                /** @description Registered graph entry */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GraphInfo"];
                    };
                };
                /** @description Validation error or invalid repo path */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graphs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a registered graph */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Graph removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Graph not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Cannot remove the default graph */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update graph settings */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateGraphBody"];
                };
            };
            responses: {
                /** @description Updated graph entry */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GraphInfo"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Graph not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/repos/onboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Onboard a repository
         * @description Server-side repo onboarding: runs allod init if needed, generates a signing key, registers the graph, and optionally indexes. Returns a step list with per-step status.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OnboardRepoBody"];
                };
            };
            responses: {
                /** @description Onboarding complete — graph registered */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnboardRepoResult"];
                    };
                };
                /** @description Onboarding failed — step list included in body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/code/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Code file tree
         * @description Nested directory tree of all indexed SourceFile nodes. Only available for repo graphs.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Nested file tree */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            tree: unknown[];
                        };
                    };
                };
                /** @description Not a repo graph */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/code/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Code file view
         * @description View a single SourceFile with its declared items. 404 if path is not indexed.
         */
        get: {
            parameters: {
                query: {
                    path: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File view with declared items */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodeFileView"];
                    };
                };
                /** @description Not a repo graph, or missing path param */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Path not indexed */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/code/item/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Code item view
         * @description Single code item (function, class, etc.) with callers and callees.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    nodeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Item view */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodeItemView"];
                    };
                };
                /** @description Not a repo graph */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Node not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/code/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Policy region membership
         * @description Maps policy rules to the file paths they match via git_checklist.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Region rules */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            rules: components["schemas"]["RegionRule"][];
                        };
                    };
                };
                /** @description Not a repo graph */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/code/neighborhood": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Code neighborhood graph
         * @description Nodes and edges one hop from the given file path.
         */
        get: {
            parameters: {
                query: {
                    path: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Neighborhood graph */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodeNeighborhood"];
                    };
                };
                /** @description Not a repo graph or missing path param */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/code/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Working-tree file source
         * @description Read raw file content from the checkout working tree. Binary files return content:"". Files over 512 KB are truncated.
         */
        get: {
            parameters: {
                query: {
                    path: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File source content */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodeSource"];
                    };
                };
                /** @description Not a repo graph, missing path param, or path traversal attempt */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description File not found on disk */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/code/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List code comments for a file
         * @description List all standalone line-anchored code comments (review/ReviewComment@1) for the given file path. Returns both saved (admitted) and pending comments across all anchor shas.
         */
        get: {
            parameters: {
                query: {
                    path: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Code comments for the file */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            comments: components["schemas"]["CodeComment"][];
                        };
                    };
                };
                /** @description Not a repo graph or missing path parameter */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Post a code comment on a file line
         * @description Creates a standalone review/ReviewComment@1 anchored to the current HEAD sha of the repo. No Review node or part_of edge.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PostCodeCommentBody"];
                };
            };
            responses: {
                /** @description Created code comment */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PostCodeCommentResult"];
                    };
                };
                /** @description Not a repo graph or validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Signing key not found for the specified principal */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OpenAPI specification */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description This document */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/git/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List git proposals
         * @description Lists all branch-head commits as proposals with checklist and decided state. Only available for repo graphs.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Git proposals */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            proposals: components["schemas"]["GitProposal"][];
                        };
                    };
                };
                /** @description Not a repo graph */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/git/proposals/{sha}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a git proposal by sha */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sha: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Git proposal */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GitProposal"];
                    };
                };
                /** @description Not a repo graph */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Proposal not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/git/proposals/{sha}/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide a git proposal
         * @description Signs a decision record (approve/reject) via the key backend and appends it to refs/notes/allod-decisions.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sha: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DecideBody"];
                };
            };
            responses: {
                /** @description Decision result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DecideResult"];
                    };
                };
                /** @description Not a repo graph or validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Proposal not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No signing key for the given principal (code: key-missing) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/git/proposals/{sha}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reviews for a git proposal */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sha: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reviews and their comments */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            reviews: components["schemas"]["ReviewEntry"][];
                        };
                    };
                };
                /** @description Not a repo graph */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Post a code review for a git proposal
         * @description Creates a review/Review@1 node and optional review/ReviewComment@1 nodes with part_of edges.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sha: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PostReviewBody"];
                };
            };
            responses: {
                /** @description Created review artifacts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PostReviewResult"];
                    };
                };
                /** @description Not a repo graph or validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/git/proposals/{sha}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get per-file full contents for a git proposal
         * @description Returns per-file old and new content for each file changed in the commit. Binary files have empty content strings. Files over 512 KB are individually truncated. Only available for repo graphs.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sha: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Diff with full file contents */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DiffResponse"];
                    };
                };
                /** @description Not a repo graph or invalid sha */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Proposal not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/git/proposals/{sha}/push-notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push decision notes to remote
         * @description Pushes refs/notes/allod-decisions to the graph's origin remote. Returns {pushed:true} on success or {pushed:false, pushError} on failure.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sha: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Push result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            pushed: boolean;
                            pushError?: string;
                        };
                    };
                };
                /** @description Not a repo graph or no remote configured */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/git/proposals/{sha}/suggestions/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply a review suggestion as a git commit
         * @description Reads the blob at the branch tip, splices the span lines with the suggestion text, and commits the result via git plumbing (no working-tree mutation). The :sha must equal the current branch tip; concurrent pushes return 409. Binary files and old-side spans return 422.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sha: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ApplySuggestionBody"];
                };
            };
            responses: {
                /** @description New commit SHA */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApplySuggestionResult"];
                    };
                };
                /** @description Not a repo graph or validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Proposal not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Branch tip moved since the suggestion was authored (code: branch-moved) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Binary file, old-side span, or invalid span format (codes: binary-file, old-side-span, invalid-span) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/code/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List code comments for a file */
        get: {
            parameters: {
                query: {
                    path: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Code comments for the file */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            comments: components["schemas"]["CodeComment"][];
                        };
                    };
                };
                /** @description Not a repo graph or missing path param */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Post a standalone line-anchored code comment */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PostCodeCommentBody"];
                };
            };
            responses: {
                /** @description Created comment */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PostCodeCommentResult"];
                    };
                };
                /** @description Not a repo graph or validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No signing key (code: key-missing) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connector": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get connector status and config */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Connector status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectorResponse"];
                    };
                };
                /** @description Not a repo graph */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Configure the connector in credential mode */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PutConnectorBody"];
                };
            };
            responses: {
                /** @description Connector configured */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            config: components["schemas"]["ConnectorConfigView"];
                        };
                    };
                };
                /** @description Not a repo graph or invalid body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No credential found or missing origin remote */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Remove connector config */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Connector config removed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
                /** @description Not a repo graph */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connector/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a connector poll immediately */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Poll result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PollResult"];
                    };
                };
                /** @description Not a repo graph */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Connector not configured */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RememberBody: {
            /** @description Agent name performing the write */
            agent: string;
            /** @description Free-text note content */
            content: string;
        };
        CreateEntityBody: {
            agent: string;
            /** @description Entity type ref, e.g. memory/Preference@1 */
            type: string;
            attributes: {
                [key: string]: unknown;
            };
            classification?: string;
        };
        UpdateEntityBody: {
            agent: string;
            type: string;
            attributes: {
                [key: string]: unknown;
            };
            /** @description Hash of the changeset being superseded */
            prior?: string;
        };
        RelateBody: {
            agent: string;
            from: string;
            to: string;
            edgeType: string;
            attributes?: {
                [key: string]: unknown;
            };
            scratch?: boolean;
        };
        ClassifyBody: {
            agent: string;
            nodeId: string;
            term: string;
            /**
             * @description How the classification was derived; manual assertions skip the envelope rule
             * @enum {string}
             */
            basis?: "model-assisted" | "manual";
        };
        AttachDocumentBody: {
            agent: string;
            entityId: string;
            content: string;
            title?: string;
        };
        RegisterAgentBody: {
            name: string;
        };
        ProposeOntologyBody: {
            agent: string;
            packageName: string;
            ontologyYaml: string;
        };
        InstallOntologyBody: {
            docsYaml: string;
        };
        PolicyBody: {
            /** @description Complete replacement policy document (YAML or JSON) */
            policy_yaml: string;
            /** @description Authoring agent principal; omitted means the owner proposes */
            agent?: string;
        };
        AdmissionResponse: {
            /** @enum {string} */
            status: "saved" | "pending";
            hash: string;
            proposal?: unknown;
            rule?: string[];
        };
        RememberResponse: components["schemas"]["AdmissionResponse"] & {
            noteId?: string;
            changeset?: string;
        };
        ProposalView: {
            hash: string;
            agent: string;
            intent: string;
            summary: string;
            rules: string[];
            diff: {
                key: string;
                before?: unknown;
                after?: unknown;
            }[];
            isSchemaProposal: boolean;
            /** @description The existing node this proposal targets, with its resolved title; null for creates */
            subject: {
                id: string;
                title: string;
            } | null;
        };
        RecallResult: {
            id: string;
            type: string;
            content?: unknown;
            author: string;
            /** @description Provenance method (model-assisted, manual, etc.) or null for unrecorded */
            method: string | null;
            /** @description approval field; maps from the `status` query parameter */
            approval: string;
            changeset: string;
            score: number;
        };
        VerifyReport: {
            ok: boolean;
            stateHash?: string;
            degraded?: {
                id: string;
                reason: string;
            }[];
        };
        SchemaDescription: {
            entityTypes: {
                name: string;
                package?: string;
                attributes?: {
                    [key: string]: unknown;
                };
                extends?: string;
            }[];
            edgeTypes: {
                name: string;
                domain?: string;
                range?: string;
            }[];
            terms: {
                name: string;
                parent?: string;
            }[];
        };
        SessionGraphEntry: {
            id: string;
            name: string;
            /** @enum {string} */
            kind: "memory" | "repo";
        };
        SessionInfo: {
            /** @description Default MCP agent name, if set */
            defaultAgent: string | null;
            /**
             * @description Active embedder backend
             * @enum {string}
             */
            embedder: "transformers" | "hash";
            /** @description Freehold's local port */
            port: number;
            /** @description The graph's owner principal; console edits sign as this name */
            owner: string;
            /** @description Slim list of registered graphs (id, name, kind) */
            graphs: components["schemas"]["SessionGraphEntry"][];
            /** @description ID of the default graph */
            defaultGraph: string;
        };
        GraphInfo: {
            id: string;
            name: string;
            path: string;
            /** @enum {string} */
            kind: "memory" | "repo";
            autoPushNotes: boolean;
            /** @enum {string} */
            embedder: "hash" | "semantic";
            allodGraphId: string;
            originRemote: string | null;
            /** @description The principal name whose key signs decide/review operations on this graph */
            signingPrincipal: string;
        };
        RegisterGraphBody: {
            /** @description Absolute path to the repo checkout */
            path: string;
            /** @description Registry slug id; defaults to basename of path */
            id?: string;
            /** @description Display name; defaults to id */
            name?: string;
            /** @description Signing principal; defaults to 'owner' */
            signingPrincipal?: string;
        };
        UpdateGraphBody: {
            name?: string;
            autoPushNotes?: boolean;
            /** @enum {string} */
            embedder?: "hash" | "semantic";
        };
        OnboardStep: {
            /** @description Step name, e.g. 'allod init' */
            step: string;
            /** @enum {string} */
            status: "ok" | "skipped" | "failed";
            /** @description Error or skip reason */
            detail?: string;
        };
        OnboardRepoBody: {
            /** @description Absolute path to the repository checkout */
            path: string;
            /** @description Display name; defaults to basename of path */
            name?: string;
            /** @description Registry slug id; defaults to basename of path */
            id?: string;
            /** @description Signing principal; defaults to 'owner' */
            principal?: string;
            /** @description Skip the initial git index step */
            noIndex?: boolean;
            /** @description Default branch for git index; defaults to 'main' */
            defaultBranch?: string;
        };
        OnboardRepoResult: {
            steps: components["schemas"]["OnboardStep"][];
            entry: components["schemas"]["GraphInfo"];
            /** @description Absolute path to the generated key file */
            keyPath: string;
            /** @description Principal whose key was generated or verified */
            principal: string;
        };
        CodeItem: {
            nodeId: string;
            type: string;
            name: string;
            signature?: string;
            span?: string;
            terms: string[];
            filePath?: string;
        };
        CodeFileView: {
            path: string;
            language?: string;
            nodeId: string;
            blobRef?: string;
            terms: string[];
            items: components["schemas"]["CodeItem"][];
        };
        CodeItemView: components["schemas"]["CodeItem"] & {
            callersIn: components["schemas"]["CodeItem"][];
            callsOut: components["schemas"]["CodeItem"][];
        };
        RegionRule: {
            rule: string;
            region?: string;
            reviewers?: unknown;
            paths: string[];
        };
        CodeNeighborhood: {
            nodes: {
                id: string;
                label: string;
                type: string;
                terms: string[];
            }[];
            edges: {
                id: string;
                from: string;
                to: string;
                type: string;
            }[];
        };
        ConnectorStatus: {
            /** @description ISO timestamp of last successful poll */
            lastPollAt?: string;
            /** @description Errors from last poll cycle */
            lastErrors?: string[];
        };
        ConnectorConfigView: {
            /**
             * @description Authentication mode
             * @enum {string}
             */
            mode: "credential" | "app";
            owner: string;
            repo: string;
            pollIntervalSec: number;
            webhooksEnabled: boolean;
            appId?: string;
            appSlug?: string;
            installationId?: string;
        };
        ConnectorResponse: {
            configured: boolean;
            config?: components["schemas"]["ConnectorConfigView"];
            status: components["schemas"]["ConnectorStatus"];
        };
        PutConnectorBody: {
            /**
             * @description Credential mode uses gh CLI token discovery
             * @enum {string}
             */
            mode: "credential";
            /** @description Poll interval in seconds (default 300) */
            pollIntervalSec?: number;
            /** @description Enable webhook delivery (requires publicUrl) */
            webhooksEnabled?: boolean;
            /** @description Public URL for webhook delivery */
            publicUrl?: string;
        } | {
            /** @description Enable or disable webhook delivery */
            webhooksEnabled: boolean;
            /** @description Public URL for webhook delivery */
            publicUrl?: string;
        };
        PollResult: {
            /** @description Number of events processed */
            events: number;
            /** @description Non-fatal errors encountered during poll */
            errors: string[];
            /** @description Number of items unchanged */
            unchanged: number;
        };
        CodeComment: {
            commentId: string;
            body: string;
            span: string;
            /** @enum {string} */
            status: "open";
            author: string;
            anchorSha: string;
            currentHead: boolean;
        };
        PostCodeCommentBody: {
            /** @description Repo-relative file path */
            path: string;
            /** @description Line span, e.g. L10 or L10-L20 */
            span: string;
            /** @description Comment text */
            body: string;
            /** @description Principal name signing the comment */
            by: string;
        };
        PostCodeCommentResult: {
            commentId: string;
            /** @enum {string} */
            status: "saved" | "pending";
            anchorSha: string;
        };
        GitProposalPath: {
            verb: string;
            path: string;
            regions: string[];
            indexed: boolean;
        };
        GitProposalCheck: {
            name: string;
            status: string;
            conclusion?: string | null;
        };
        GitProposal: {
            sha: string;
            ref: string;
            author: string;
            timestamp: string;
            message: string;
            target: string;
            matched: string[];
            checklist: unknown[];
            unmet: string[];
            /** @enum {string} */
            decided: "undecided" | "approved" | "rejected";
            paths: components["schemas"]["GitProposalPath"][];
            checks?: components["schemas"]["GitProposalCheck"][];
        };
        DecideBody: {
            /** @enum {string} */
            verdict: "approve" | "reject";
            /** @description Principal name performing the decision */
            by: string;
        };
        DecideResult: {
            /** @enum {string} */
            outcome: "approved" | "rejected";
            pushed: boolean;
            /** @description True when push was not attempted because auto-push is off or no remote is configured. */
            pushSkipped?: boolean;
            pushError?: string;
        } | {
            /** @enum {string} */
            outcome: "incomplete";
            unmet: string[];
        };
        ReviewCommentInput: {
            body: string;
            anchor?: string;
            span?: string;
        };
        PostReviewBody: {
            /** @enum {string} */
            verdict: "approve" | "approve-with-comments" | "request-changes";
            body?: string;
            /** @description Author principal */
            by: string;
            comments?: components["schemas"]["ReviewCommentInput"][];
        };
        PostReviewResult: {
            reviewId: string;
            commentIds: string[];
            /** @enum {string} */
            status: "saved" | "pending";
        };
        ReviewComment: {
            commentId: string;
            body?: string;
            anchor?: string;
            span?: string;
            status: string;
            external_source?: string;
            claimed_author?: string;
        };
        ReviewEntry: {
            reviewId: string;
            verdict: string;
            body?: string;
            commit: string;
            author: string;
            /** @enum {string} */
            status: "saved" | "pending";
            comments: components["schemas"]["ReviewComment"][];
        };
        DiffFile: {
            path: string;
            oldPath?: string;
            /** @enum {string} */
            verb: "A" | "M" | "D" | "R";
            binary: boolean;
            oldContent: string;
            newContent: string;
            truncated: boolean;
        };
        DiffResponse: {
            files: components["schemas"]["DiffFile"][];
            truncated: boolean;
        };
        ApplySuggestionBody: {
            /** @description Branch name (without refs/heads/ prefix) */
            branch: string;
            /** @description Repo-relative file path */
            path: string;
            /** @description Additions-side span, e.g. "L5" or "L5-L9" */
            span: string;
            /** @description Replacement text for the spanned lines */
            suggestion: string;
            /** @description Principal name for commit attribution */
            by: string;
        };
        ApplySuggestionResult: {
            /** @description SHA of the new commit */
            newSha: string;
        };
        CodeComment: {
            commentId: string;
            body: string;
            span: string;
            /** @enum {string} */
            status: "open";
            author: string;
            anchorSha: string;
            currentHead: boolean;
        };
        PostCodeCommentBody: {
            path: string;
            span: string;
            body: string;
            by: string;
        };
        PostCodeCommentResult: {
            commentId: string;
            /** @enum {string} */
            status: "saved" | "pending";
            anchorSha: string;
        };
        MemoryIndexEntry: {
            id: string;
            type: string;
            /** @description Display title derived from attributes (title, name, statement, first line) */
            title: string;
            approval: string;
            author: string;
            updatedAt: string;
            /** @description Taxonomy terms from fold state */
            terms: string[];
        };
        GraphNode: {
            id: string;
            type: string;
            title: string;
            approval: string;
            terms: string[];
        };
        GraphEdge: {
            id: string;
            type: string;
            from: string;
            to: string;
        };
        MemoryGraphView: {
            nodes: components["schemas"]["GraphNode"][];
            edges: components["schemas"]["GraphEdge"][];
            /** @description True when the node cap cut the listing short */
            truncated: boolean;
        };
        CodeSource: {
            path: string;
            /** @description UTF-8 source text (empty when binary) */
            content: string;
            /** @description True when file exceeded 512 KB read limit */
            truncated: boolean;
            /** @description True when a NUL byte was detected in the first 8 KB */
            binary: boolean;
            /** @description File size in bytes (full file, not truncated) */
            size: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
