/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodeRouteImport } from './routes/code'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as SchemaRouteImport } from './routes/schema'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as CodeFileRouteImport } from './routes/code.file'
import { Route as CodeGraphRouteImport } from './routes/code.graph'
import { Route as CodeItemRouteImport } from './routes/code.item'
import { Route as MemoryIdRouteImport } from './routes/memory.$id'
import { Route as MemoryGraphRouteImport } from './routes/memory.graph'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaRoute = SchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeFileRoute = CodeFileRouteImport.update({
  id: '/file',
  path: '/file',
  getParentRoute: () => CodeRoute,
} as any)
const CodeGraphRoute = CodeGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => CodeRoute,
} as any)
const CodeItemRoute = CodeItemRouteImport.update({
  id: '/item',
  path: '/item',
  getParentRoute: () => CodeRoute,
} as any)
const MemoryIdRoute = MemoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MemoryRoute,
} as any)
const MemoryGraphRoute = MemoryGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => MemoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/code': typeof CodeRouteWithChildren
  '/inbox': typeof InboxRoute
  '/memory': typeof MemoryRouteWithChildren
  '/policy': typeof PolicyRoute
  '/schema': typeof SchemaRoute
  '/settings': typeof SettingsRoute
  '/verify': typeof VerifyRoute
  '/code/file': typeof CodeFileRoute
  '/code/graph': typeof CodeGraphRoute
  '/code/item': typeof CodeItemRoute
  '/memory/$id': typeof MemoryIdRoute
  '/memory/graph': typeof MemoryGraphRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/code': typeof CodeRouteWithChildren
  '/inbox': typeof InboxRoute
  '/memory': typeof MemoryRouteWithChildren
  '/policy': typeof PolicyRoute
  '/schema': typeof SchemaRoute
  '/settings': typeof SettingsRoute
  '/verify': typeof VerifyRoute
  '/code/file': typeof CodeFileRoute
  '/code/graph': typeof CodeGraphRoute
  '/code/item': typeof CodeItemRoute
  '/memory/$id': typeof MemoryIdRoute
  '/memory/graph': typeof MemoryGraphRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/code': typeof CodeRouteWithChildren
  '/inbox': typeof InboxRoute
  '/memory': typeof MemoryRouteWithChildren
  '/policy': typeof PolicyRoute
  '/schema': typeof SchemaRoute
  '/settings': typeof SettingsRoute
  '/verify': typeof VerifyRoute
  '/code/file': typeof CodeFileRoute
  '/code/graph': typeof CodeGraphRoute
  '/code/item': typeof CodeItemRoute
  '/memory/$id': typeof MemoryIdRoute
  '/memory/graph': typeof MemoryGraphRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/code'
    | '/inbox'
    | '/memory'
    | '/policy'
    | '/schema'
    | '/settings'
    | '/verify'
    | '/code/file'
    | '/code/graph'
    | '/code/item'
    | '/memory/$id'
    | '/memory/graph'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/code'
    | '/inbox'
    | '/memory'
    | '/policy'
    | '/schema'
    | '/settings'
    | '/verify'
    | '/code/file'
    | '/code/graph'
    | '/code/item'
    | '/memory/$id'
    | '/memory/graph'
  id:
    | '__root__'
    | '/'
    | '/code'
    | '/inbox'
    | '/memory'
    | '/policy'
    | '/schema'
    | '/settings'
    | '/verify'
    | '/code/file'
    | '/code/graph'
    | '/code/item'
    | '/memory/$id'
    | '/memory/graph'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeRoute: typeof CodeRouteWithChildren
  InboxRoute: typeof InboxRoute
  MemoryRoute: typeof MemoryRouteWithChildren
  PolicyRoute: typeof PolicyRoute
  SchemaRoute: typeof SchemaRoute
  SettingsRoute: typeof SettingsRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schema': {
      id: '/schema'
      path: '/schema'
      fullPath: '/schema'
      preLoaderRoute: typeof SchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code/file': {
      id: '/code/file'
      path: '/file'
      fullPath: '/code/file'
      preLoaderRoute: typeof CodeFileRouteImport
      parentRoute: typeof CodeRoute
    }
    '/code/graph': {
      id: '/code/graph'
      path: '/graph'
      fullPath: '/code/graph'
      preLoaderRoute: typeof CodeGraphRouteImport
      parentRoute: typeof CodeRoute
    }
    '/code/item': {
      id: '/code/item'
      path: '/item'
      fullPath: '/code/item'
      preLoaderRoute: typeof CodeItemRouteImport
      parentRoute: typeof CodeRoute
    }
    '/memory/$id': {
      id: '/memory/$id'
      path: '/$id'
      fullPath: '/memory/$id'
      preLoaderRoute: typeof MemoryIdRouteImport
      parentRoute: typeof MemoryRoute
    }
    '/memory/graph': {
      id: '/memory/graph'
      path: '/graph'
      fullPath: '/memory/graph'
      preLoaderRoute: typeof MemoryGraphRouteImport
      parentRoute: typeof MemoryRoute
    }
  }
}

interface CodeRouteChildren {
  CodeFileRoute: typeof CodeFileRoute
  CodeGraphRoute: typeof CodeGraphRoute
  CodeItemRoute: typeof CodeItemRoute
}

const CodeRouteChildren: CodeRouteChildren = {
  CodeFileRoute: CodeFileRoute,
  CodeGraphRoute: CodeGraphRoute,
  CodeItemRoute: CodeItemRoute,
}

const CodeRouteWithChildren = CodeRoute._addFileChildren(CodeRouteChildren)

interface MemoryRouteChildren {
  MemoryIdRoute: typeof MemoryIdRoute
  MemoryGraphRoute: typeof MemoryGraphRoute
}

const MemoryRouteChildren: MemoryRouteChildren = {
  MemoryIdRoute: MemoryIdRoute,
  MemoryGraphRoute: MemoryGraphRoute,
}

const MemoryRouteWithChildren =
  MemoryRoute._addFileChildren(MemoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeRoute: CodeRouteWithChildren,
  InboxRoute: InboxRoute,
  MemoryRoute: MemoryRouteWithChildren,
  PolicyRoute: PolicyRoute,
  SchemaRoute: SchemaRoute,
  SettingsRoute: SettingsRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
